<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KoltiSkills</name>
   <tag></tag>
   <elementGuidId>c4627771-2bea-4f67-9259-648882cf2820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zfmoreContainer1label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zfmoreContainer1label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7d1190ad-1d39-4df2-9bbe-2f748d197244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>1944228a-c7b6-43f3-97ed-51ea9bbd5d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zfmoreContainer1label</value>
      <webElementGuid>09859416-99ea-43cc-8cd2-e1cd8a4fe152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KoltiSkills</value>
      <webElementGuid>737ff7a8-1df3-4222-9d81-ec824c54db8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zfmoreContainer1label&quot;)</value>
      <webElementGuid>74ae32ee-7eb5-4a93-93d0-f59682b1d6ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zfmoreContainer1label']</value>
      <webElementGuid>5fd7f67f-428e-49ad-8d5b-b422468910c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zfmoreContainer1']/a/div/div/p</value>
      <webElementGuid>3e01e03d-74d5-41a9-8c74-a452d30fb09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[8]</value>
      <webElementGuid>4f0873be-268b-40e1-a253-4a0f240d28db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/following::p[8]</value>
      <webElementGuid>8addd5bf-c6d2-4bab-8785-c416090284e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::p[3]</value>
      <webElementGuid>1b827785-12b9-460c-a85d-7ea2f7b77411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a/div/div/p</value>
      <webElementGuid>1f33c4f0-1237-4959-856e-91bbdf79fbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zfmoreContainer1label' and (text() = 'KoltiSkills' or . = 'KoltiSkills')]</value>
      <webElementGuid>ccbd81b2-60a8-489d-b4f2-c894afc66579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
