<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KoltiTrace</name>
   <tag></tag>
   <elementGuidId>abba540b-20da-4d6d-b2d0-a637bf09d8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zfmoreContainer0label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zfmoreContainer0label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dd19069d-aef5-470e-bb37-c74094866b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>7824e8e8-43ba-47e6-954e-b267d573dec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zfmoreContainer0label</value>
      <webElementGuid>be42ed72-22c4-4702-9185-0686d6a277b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KoltiTrace</value>
      <webElementGuid>59ec2826-5991-476a-9af5-cd846071cb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zfmoreContainer0label&quot;)</value>
      <webElementGuid>71db1999-e530-43be-95cd-7196d3814719</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zfmoreContainer0label']</value>
      <webElementGuid>51765f94-a567-4ed7-a535-903ab5e5c683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zfmoreContainer0']/a/div/div/p</value>
      <webElementGuid>800b8f68-e30a-4457-8793-3a9367e3bb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[7]</value>
      <webElementGuid>bcd0a251-f466-4802-87e0-4187cb261bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/following::p[7]</value>
      <webElementGuid>883e2ac4-af57-49a0-b9d6-cba5ed8ed8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::p[4]</value>
      <webElementGuid>9af6ee08-a70b-4281-869e-6d3448c9ef8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/div/div/p</value>
      <webElementGuid>d12f3950-5ba3-4717-ab62-c3872f81d27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zfmoreContainer0label' and (text() = 'KoltiTrace' or . = 'KoltiTrace')]</value>
      <webElementGuid>49ac2b25-ac57-46f7-8d3f-a350827cb909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
