<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KoltiPay</name>
   <tag></tag>
   <elementGuidId>a3afb64f-f912-4abe-8671-4857d2c33353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zfmoreContainer3label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zfmoreContainer3label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>22dd3bd0-c905-41bd-80c7-4a283107c715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>910b7b99-4949-4232-85c1-ac95a910269d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zfmoreContainer3label</value>
      <webElementGuid>409fd6a6-1087-4b02-a6b5-a3e2107ba110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KoltiPay</value>
      <webElementGuid>997cfba2-86ae-4179-a05a-38bd05381f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zfmoreContainer3label&quot;)</value>
      <webElementGuid>b773e1c9-74ee-4473-b8b1-568330c760c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zfmoreContainer3label']</value>
      <webElementGuid>1a6c8f54-b515-47cb-bc91-4c9e6423e6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zfmoreContainer3']/a/div/div/p</value>
      <webElementGuid>227f3aa8-001c-40d5-bbdf-8ceb36b600bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[10]</value>
      <webElementGuid>a75da7d1-6abc-4931-af1c-98b678d320c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/following::p[10]</value>
      <webElementGuid>307e3774-47ff-4eb4-b0be-3ebb1e92cce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::p[1]</value>
      <webElementGuid>05f38be8-0db0-46f4-83b8-3eb2873bd6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a/div/div/p</value>
      <webElementGuid>f9e6be0e-31d6-4b69-9055-c4d0f11b7738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zfmoreContainer3label' and (text() = 'KoltiPay' or . = 'KoltiPay')]</value>
      <webElementGuid>67eb4577-1c80-413f-a1d5-77b60f528474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
