<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Solutions</name>
   <tag></tag>
   <elementGuidId>dcf791cf-5182-4278-9d24-0290e316d61a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zf2label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zf2label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>631b5a58-76d1-4877-b2e6-b44baaec1811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>7041fb9e-a563-4eae-afcc-e6f6880b42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zf2label</value>
      <webElementGuid>31daf2ef-ddfa-4f0f-9cb8-d5fc1fd5b209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solutions</value>
      <webElementGuid>6b8c046a-d71b-4e79-bd7a-017a3f3d7d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zf2label&quot;)</value>
      <webElementGuid>635d55cf-cdb2-4986-96f2-714a26a0662e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zf2label']</value>
      <webElementGuid>8cdd6673-319c-43cb-a776-b4c51faecedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zf2']/a/div/div/p</value>
      <webElementGuid>27340ff9-ba60-4656-8563-9022e016da9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::p[3]</value>
      <webElementGuid>47e672cf-a6fd-4a88-9b73-98b132e24d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='top of page'])[1]/following::p[3]</value>
      <webElementGuid>9d987f8e-c8a4-4b26-a930-69026638634f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrace'])[1]/preceding::p[1]</value>
      <webElementGuid>8d8dc681-55fa-4171-aa59-5dfa30a6f1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiSkills'])[1]/preceding::p[1]</value>
      <webElementGuid>7d31354c-d7de-486f-94ff-3255e3ce031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solutions']/parent::*</value>
      <webElementGuid>d4b036a0-2c8a-4457-8792-4eb74b7b7671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div/div/p</value>
      <webElementGuid>3534c8e9-4ef8-4128-a0c9-a1ee4be6beb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zf2label' and (text() = 'Solutions' or . = 'Solutions')]</value>
      <webElementGuid>f5fbdde0-0415-4f45-8f9a-eb72a724dd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
