<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_About</name>
   <tag></tag>
   <elementGuidId>8edcdc83-0c9a-439a-b5fd-81ce1fbb990b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp-lcm1smiz4']/p/span/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-lcm1smiz4 > p.font_9.wixui-rich-text__text > span.wixui-rich-text__text > a.wixui-rich-text__text > span.wixui-rich-text__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>754506bd-ea78-4adb-a2d1-0b7179401b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wixui-rich-text__text</value>
      <webElementGuid>f0cd6dc8-3923-45fe-ba1e-b1642b87c3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>cc0fa510-014f-4782-9b1f-e62b89055ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-lcm1smiz4&quot;)/p[@class=&quot;font_9 wixui-rich-text__text&quot;]/span[@class=&quot;wixui-rich-text__text&quot;]/a[@class=&quot;wixui-rich-text__text&quot;]/span[@class=&quot;wixui-rich-text__text&quot;]</value>
      <webElementGuid>3c1549b4-7063-4d05-acb6-a796235bc7fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp-lcm1smiz4']/p/span/a/span</value>
      <webElementGuid>f77d7e8a-2331-4ae7-954d-ff6f33a5f0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOLTISKILLS'])[1]/following::span[3]</value>
      <webElementGuid>6e2a0d39-571a-4577-b808-4775c8a7c1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOLTITRADE'])[1]/following::span[7]</value>
      <webElementGuid>33b2476d-f10c-4a0a-8a4f-cf782929590c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/preceding::span[1]</value>
      <webElementGuid>22ae298b-880d-4f10-a6d1-5892766692d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[2]/preceding::span[3]</value>
      <webElementGuid>e1d5864f-90f1-48f5-ba51-054573a3f93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/p/span/a/span</value>
      <webElementGuid>70481be0-7dfa-4ace-8cfa-700c7c136844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'About' or . = 'About')]</value>
      <webElementGuid>f4830ee2-4551-4019-b787-29c24640fb34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
