<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Share Post__YVy73 JMR6JX</name>
   <tag></tag>
   <elementGuidId>2cfdc7c2-6cea-475e-9a2b-8e8ba8f5fc07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='new-blog-modal-root']/main/div[2]/div/div[2]/span[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._YVy73.JMR6JX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9b7191b-14f7-4ad5-a0c2-e64f9656582b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_YVy73 JMR6JX</value>
      <webElementGuid>6035cd13-6f2a-4986-af89-fa385050c07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Share via link</value>
      <webElementGuid>18236dcd-1bb2-4dc0-a647-0c86292e5430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hook</name>
      <type>Main</type>
      <value>share-button__link</value>
      <webElementGuid>ded44608-3b2c-4c08-ac03-7e035fdff4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-blog-modal-root&quot;)/main[@class=&quot;bBBxJk I2dBi2&quot;]/div[@class=&quot;FT5pQN JvTxgP blog-card-background-color&quot;]/div[@class=&quot;qnI9MQ blog-text-color blog-post-title-font&quot;]/div[@class=&quot;yxd80l&quot;]/span[@class=&quot;QrY79E&quot;]/button[@class=&quot;_YVy73 JMR6JX&quot;]</value>
      <webElementGuid>10e45e8e-35fb-4b11-87cd-7e78f48a02c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new-blog-modal-root']/main/div[2]/div/div[2]/span[4]/button</value>
      <webElementGuid>674ed006-d905-4f6b-ab3d-c80804d3c5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share Post'])[1]/following::button[4]</value>
      <webElementGuid>87c66a9e-9962-492b-8132-0f274675146d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/following::button[5]</value>
      <webElementGuid>6c6d9ed0-120b-4d67-8a25-7108daa7957a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Posts'])[1]/preceding::button[1]</value>
      <webElementGuid>1ac8250b-99e5-4b40-addc-14ebcc8cb228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::button[2]</value>
      <webElementGuid>d4e7ac28-3f30-4e4e-9e2e-8c71c36a4d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/button</value>
      <webElementGuid>0617dff9-8331-40cd-aa90-d7e0bfcd1aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
