<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cancel</name>
   <tag></tag>
   <elementGuidId>8656a3ad-ca9e-4a20-b7c9-9440e0bb5c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='new-blog-modal-root']/main/div[2]/div/div[2]/div/div[2]/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.I4gY7Y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8be4b48-1574-4ec8-aaae-88395411af3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>I4gY7Y</value>
      <webElementGuid>7d26ca13-cf9d-47f7-876b-fea09fa9677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>cfb1ca92-ac25-424c-bf95-4c9ac58ae7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-blog-modal-root&quot;)/main[@class=&quot;bBBxJk I2dBi2&quot;]/div[@class=&quot;FT5pQN JvTxgP blog-card-background-color&quot;]/div[@class=&quot;qnI9MQ blog-text-color blog-post-title-font&quot;]/div[@class=&quot;yxd80l&quot;]/div[@class=&quot;gDptQ4&quot;]/div[@class=&quot;TF4qdp&quot;]/div[@class=&quot;s5nF1u&quot;]/div[@class=&quot;gLee2N&quot;]/button[@class=&quot;ntKNd_ v5HbN_ button-group__secondary-button blog-post-description-font blog-button-border-color blog-button-secondary-text-color EwBavj&quot;]/span[@class=&quot;I4gY7Y&quot;]</value>
      <webElementGuid>8baf517a-8319-4b17-956c-5e8963b80425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='new-blog-modal-root']/main/div[2]/div/div[2]/div/div[2]/div/div/button/span</value>
      <webElementGuid>026f686f-2b0c-4a87-b11b-c900b22e7fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share Link'])[1]/following::span[1]</value>
      <webElementGuid>0c686f7f-e3a2-4688-a8e0-ec7ee7fc2c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/following::span[3]</value>
      <webElementGuid>3c7c8736-c825-4199-bafc-debb2b49d194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Link'])[1]/preceding::span[1]</value>
      <webElementGuid>329fdb61-6ed6-421c-9fff-ef509089a28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Posts'])[1]/preceding::span[2]</value>
      <webElementGuid>fc492c6b-490e-4110-b754-f8d33969906d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>09b43c4a-247c-4a5d-86fc-0d556f2b490e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>a331ea9e-b785-4348-ba44-f3c21a85ed8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>e39c6686-3439-42b6-bd93-938d9af407f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
