<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_About Us</name>
   <tag></tag>
   <elementGuidId>22746205-c559-401d-a7d3-3a04ac947d8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp-lclnde61']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.font_8.wixui-rich-text__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ca274332-0641-45b4-b583-b5530c437725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_8 wixui-rich-text__text</value>
      <webElementGuid>69c906cf-0aab-4afc-a922-1445a700e1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About Us</value>
      <webElementGuid>98a4c217-737c-409d-902e-194a82f19f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-lclnde61&quot;)/p[@class=&quot;font_8 wixui-rich-text__text&quot;]</value>
      <webElementGuid>02fd670e-de92-48bb-a221-c9fa87db6e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp-lclnde61']/p</value>
      <webElementGuid>1514a373-86fc-4eb8-930e-14e373ba6ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/following::p[1]</value>
      <webElementGuid>5d66b660-17f2-4fc2-9ca4-1de9f4d2205d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[7]</value>
      <webElementGuid>7540f7f3-db1f-4beb-93e0-87284bd8db29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEYOND TRACEABILITY'])[1]/preceding::p[1]</value>
      <webElementGuid>f1710447-93f3-4408-9970-8b7bc6dcd9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p</value>
      <webElementGuid>750c9d08-bb02-4c4e-9eb7-8187f41ad011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'About Us' or . = 'About Us')]</value>
      <webElementGuid>4bb6bcc8-54c2-4617-a74f-7aa72f06652a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
