<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_About</name>
   <tag></tag>
   <elementGuidId>6d56be23-bc99-44af-b21e-c774c3e3cfd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zf1label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zf1label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>86ed7165-da5f-4d31-ac2c-193d1791e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>5d79d145-1d67-4e1e-a403-0b8d19c16317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zf1label</value>
      <webElementGuid>479d4a48-1bda-4205-8d3c-63f136c6c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>7ac72d36-d20e-4f79-b00a-6b7c7fe23713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zf1label&quot;)</value>
      <webElementGuid>96524485-7742-4ac6-887a-41356a981c89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zf1label']</value>
      <webElementGuid>29a25b4b-bfb0-4129-b582-f660a9270665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zf1']/a/div/div/p</value>
      <webElementGuid>483b3dc3-e3e2-4a40-a642-1a87fb6a1156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::p[2]</value>
      <webElementGuid>0bc48304-7e9b-430d-899b-3ac2504c6a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='top of page'])[1]/following::p[2]</value>
      <webElementGuid>269a54f6-f660-4a9d-b298-ac9439bd11a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrace'])[1]/preceding::p[2]</value>
      <webElementGuid>b835b9c0-ba6b-47a1-a437-8445c57b5e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiSkills'])[1]/preceding::p[2]</value>
      <webElementGuid>576eb539-2902-4fa9-ab13-e446489b6929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About']/parent::*</value>
      <webElementGuid>8291daea-7632-462e-9b86-6e89a28c6073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div/p</value>
      <webElementGuid>0f9eb1ed-e1f6-4615-a0a9-c663526be4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zf1label' and (text() = 'About' or . = 'About')]</value>
      <webElementGuid>8a086623-2224-4a4f-b009-fd98d7f085af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
