<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Trading, Warehousing, and Distribution Services</name>
   <tag></tag>
   <elementGuidId>fa3a8b89-d8b2-4fb3-a325-33801c9c5287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp-l1prxbmt']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.font_0.wixui-rich-text__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5999baad-f8d1-4b42-9283-6ab4de3abd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font_0 wixui-rich-text__text</value>
      <webElementGuid>8fb5a807-24ae-4954-920b-94c7b925b609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trading, Warehousing, and Distribution Services</value>
      <webElementGuid>eac3470d-8664-41a2-9c2c-548c354e7103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-l1prxbmt&quot;)/h1[@class=&quot;font_0 wixui-rich-text__text&quot;]</value>
      <webElementGuid>5c1cf010-25b3-47e6-8850-53446f0b9bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp-l1prxbmt']/h1</value>
      <webElementGuid>7630169d-e123-4e4d-a412-1ea87ffe311a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/following::h1[1]</value>
      <webElementGuid>246ed60e-6310-44d6-a5df-38e09f34c381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::h1[1]</value>
      <webElementGuid>24326036-55f7-40d4-a7d6-7fd8448e9b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talk to the Expert'])[1]/preceding::h1[1]</value>
      <webElementGuid>0bb6594d-7344-4714-aa8d-6fad08d6c2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>54078558-6913-4e38-af31-a062f100f65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Trading, Warehousing, and Distribution Services' or . = 'Trading, Warehousing, and Distribution Services')]</value>
      <webElementGuid>b4707d64-d3ac-44ad-ac74-d4611ac8895e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
