<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_KoltiTrade</name>
   <tag></tag>
   <elementGuidId>d2072ae2-dcdf-435e-9a6d-41e2a88505c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zfmoreContainer2label']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'comp-keidh9zfmoreContainer2label' and (text() = 'KoltiTrade' or . = 'KoltiTrade')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zfmoreContainer2label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>498f3bde-52d5-4478-b8d0-0c80dbc91d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>541f047b-2e8b-4931-a518-cd17df834406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zfmoreContainer2label</value>
      <webElementGuid>77e1016b-25f5-419d-816f-b484bcd50c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KoltiTrade</value>
      <webElementGuid>8ffe3451-a697-4f16-ad8a-e3ecc7663a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zfmoreContainer2label&quot;)</value>
      <webElementGuid>d05bbc3d-3b53-4ba6-ab5e-ca1ed37adfd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zfmoreContainer2label']</value>
      <webElementGuid>50bcef27-dbad-4e61-8c03-19826205628b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zfmoreContainer2']/a/div/div/p</value>
      <webElementGuid>67056425-71b8-436a-8f68-28973eb6acfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[9]</value>
      <webElementGuid>ee4c56fb-083d-44ce-a3ea-24148f182f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/following::p[9]</value>
      <webElementGuid>8fd14f7c-3e3c-403e-ba5a-c9de848d6a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::p[2]</value>
      <webElementGuid>ee531cef-18f8-4615-9ace-409254f943b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a/div/div/p</value>
      <webElementGuid>572fed1d-2c40-4c46-9c6c-393e26fbab18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zfmoreContainer2label' and (text() = 'KoltiTrade' or . = 'KoltiTrade')]</value>
      <webElementGuid>b9440521-4d24-4daf-86ea-22fa9736eec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
