<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Feature Articles</name>
   <tag></tag>
   <elementGuidId>339a87bc-9bcf-42a6-a783-7c692119d40f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp-l8qoximp']/h2/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.wixui-rich-text__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db963092-1436-4a9a-a22d-8faeddcefab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wixui-rich-text__text</value>
      <webElementGuid>139029f4-647a-4d0c-b995-f0f2a2254540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feature Articles:</value>
      <webElementGuid>e3e42ffa-e2f7-4061-8b1a-1676d5b92e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-l8qoximp&quot;)/h2[@class=&quot;font_2 wixui-rich-text__text&quot;]/span[@class=&quot;wixui-rich-text__text&quot;]</value>
      <webElementGuid>55e3e159-2476-49d8-a12a-ccafee4622d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp-l8qoximp']/h2/span</value>
      <webElementGuid>1aff37ff-3e02-425f-a769-87451cdf0865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmer Story'])[2]/following::span[1]</value>
      <webElementGuid>4b8fb06a-2b15-4cec-87e6-63f9a71a1909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 8, 2022'])[1]/following::span[2]</value>
      <webElementGuid>9194ce29-40dd-4613-a7c4-a0837819190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Farmers', &quot;'&quot;, ' Story:')])[1]/preceding::span[1]</value>
      <webElementGuid>d29cee4a-7e6c-425d-b1e9-f30a1d2bd852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News:'])[1]/preceding::span[2]</value>
      <webElementGuid>524f8d67-e1e4-4c3e-8532-ee5d02aff608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Feature Articles:']/parent::*</value>
      <webElementGuid>032be530-d8dc-4f66-8564-480e0b1e6922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/span</value>
      <webElementGuid>e33ec61e-013e-4969-aa4d-578d84097172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Feature Articles:' or . = 'Feature Articles:')]</value>
      <webElementGuid>64a9cfa6-cdcd-462b-a75d-37d693a90801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
