<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In</name>
   <tag></tag>
   <elementGuidId>60e18209-bdef-417d-942d-44ea01db706c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalRegister___BV_modal_body_']/div[2]/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.pointer.font-weight-semi-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>317bc069-549e-471c-b8bb-e8432693e528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>open-login</value>
      <webElementGuid>e8829914-bbd9-4b33-82b5-ee4ff2fac8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer font-weight-semi-bold</value>
      <webElementGuid>15661ba4-2cf2-4eba-8dd6-4c7cdb29a59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>c35beaa3-e4fd-4ea2-a000-00482705dde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalRegister___BV_modal_body_&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 text-center&quot;]/p[@class=&quot;forgot font-weight-regular&quot;]/a[@class=&quot;pointer font-weight-semi-bold&quot;]</value>
      <webElementGuid>242246ee-8cd3-4330-bdb2-a0db533ef309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalRegister___BV_modal_body_']/div[2]/div/p/a</value>
      <webElementGuid>167646ba-ede0-4f9f-b319-63bce0a684ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In')]</value>
      <webElementGuid>987ea6c0-e8ee-4d8a-9437-01458a5c50fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::a[1]</value>
      <webElementGuid>57fbca10-73d6-4a82-abcb-22f4cd895231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::a[1]</value>
      <webElementGuid>6a826a7b-dc6e-41d8-ba38-0fc5724eb3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[1]/preceding::a[1]</value>
      <webElementGuid>9bc6b07b-be29-43c9-8405-e2cddbe1ed33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full Name'])[1]/preceding::a[1]</value>
      <webElementGuid>1152cc27-867f-4f17-bf1b-de7d9688a72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>3169c7b9-b701-48bb-8761-3815c6c9c168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e9f81cec-6602-4ec2-86d4-5d92068226f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>41fa6762-aba5-4e84-be25-c133ec650df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
