<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__lg-next lg-icon</name>
   <tag></tag>
   <elementGuidId>908124a4-d907-4fcf-9095-3facec09ef5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.lg-next.lg-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d158ce30-c865-40df-b4bf-a90ef11b82b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d0092bf-ff54-4fa8-887b-265eab38ec6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next slide</value>
      <webElementGuid>9793cf63-ad05-45b6-9121-da0926c71a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg-next lg-icon</value>
      <webElementGuid>47ed7209-725b-45fb-846c-e0521086e557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;lg-on&quot;]/div[@class=&quot;lg-outer lg-start-zoom lg-use-css3 lg-css3 lg-fade lg-grab lg-show-after-load lg-hide-download lg-visible lg-hide-items&quot;]/div[@class=&quot;lg&quot;]/div[@class=&quot;lg-actions&quot;]/button[@class=&quot;lg-next lg-icon&quot;]</value>
      <webElementGuid>f5931b46-79ae-4b6b-ab69-7d2786bdb2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>06ea6fb4-b0ad-459d-8ff2-0103aef36309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9cb1e0ce-427e-44d9-9d58-c82d1c6cc1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>e4301212-a548-431b-a03e-b55d1c389d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
