<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Start Your Career in Agritech and Cultivate a Greener Earth</name>
   <tag></tag>
   <elementGuidId>a5fae561-c24b-429a-ac4b-bbbff7c9a005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/main/section/div/div/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>6a5263b8-f450-4dbd-9116-a45efddfbe64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>2d7c5503-c404-482e-96b9-3796ad498178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Your Career in Agritech and Cultivate a Greener Earth​</value>
      <webElementGuid>eeda21b8-2dc1-44df-a225-9169c390d1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/main[1]/section[@class=&quot;hero&quot;]/div[@class=&quot;gradient&quot;]/div[@class=&quot;centered&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-between&quot;]/div[@class=&quot;col-lg-6 col-12&quot;]/h1[@class=&quot;title&quot;]</value>
      <webElementGuid>a9cea0ab-dd26-42a3-b3dc-31ce886c4725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/main/section/div/div/div/div/div/h1</value>
      <webElementGuid>3855db7d-e20b-4722-8046-2750569d4e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::h1[1]</value>
      <webElementGuid>f3702813-81a6-49d8-b237-37e91e7f2dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us'])[2]/following::h1[1]</value>
      <webElementGuid>5c7b22fb-5243-4905-b0c3-8cc325ab6a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Jobs'])[1]/preceding::h1[1]</value>
      <webElementGuid>a27b465d-3342-4f7b-b462-b2b8e35a229f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Locations'])[1]/preceding::h1[1]</value>
      <webElementGuid>7382ecd3-3040-4a4e-a120-4de35e9bc91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Your Career in Agritech and Cultivate a Greener Earth​']/parent::*</value>
      <webElementGuid>145505b7-cff9-4463-ac2b-6f11182c54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>fcc11ac9-fa5a-4923-910f-2f1d997a7204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Start Your Career in Agritech and Cultivate a Greener Earth​' or . = 'Start Your Career in Agritech and Cultivate a Greener Earth​')]</value>
      <webElementGuid>a2168bb3-5123-4400-b7a8-f0b43877ab77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
