<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Job Search</name>
   <tag></tag>
   <elementGuidId>5124ae61-b122-4f33-beeb-5b4f37683c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/main/main/section/div[2]/div/div/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h6.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>4beeb9b7-ef85-410d-9800-cd479d167d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>ff3d3a4f-ee50-4d86-bc43-f5a3ed372971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Search</value>
      <webElementGuid>b1fc3de2-381a-44dc-b8f8-a3461c9f7a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/main[1]/main[1]/section[@class=&quot;hero-list-job&quot;]/div[@class=&quot;bg-green container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;px-0 d-flex justify-content-between flex-column flex-md-row col-12&quot;]/h6[@class=&quot;title&quot;]</value>
      <webElementGuid>2099cdb6-3df0-43fd-a55f-20e704e63782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/main/main/section/div[2]/div/div/div/h6</value>
      <webElementGuid>655aa59e-16e6-418d-b17e-3cd85941cdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Journey to Cultivate a Better Future Begins Here'])[1]/following::h6[1]</value>
      <webElementGuid>b14de3ac-41de-4e5d-886f-3cce614c8b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::h6[1]</value>
      <webElementGuid>1cd21248-90e1-4a92-817d-e47a60cb4853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Locations'])[1]/preceding::h6[1]</value>
      <webElementGuid>94baff76-4b68-4a7b-a33e-f4935432f199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Assurance Lead'])[1]/preceding::h6[1]</value>
      <webElementGuid>56cceca7-8150-413f-95a9-1f1f7e31a56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Job Search']/parent::*</value>
      <webElementGuid>d3fda2dd-b972-4aa8-8c81-3ae7c8d2e911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>8d357981-ed2a-4053-8d27-ceb3fb8a111b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Job Search' or . = 'Job Search')]</value>
      <webElementGuid>3bd54c58-538d-4a0c-bb37-e12e96ad669c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
