<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Role</name>
   <tag></tag>
   <elementGuidId>99d665c9-4001-4557-a6cf-fad390248144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/main/main/section[3]/div[2]/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.title-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1ea6ca7a-645d-4259-9a8b-5e445f657365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-header</value>
      <webElementGuid>9c84dabf-a779-453e-b758-ed051d7e36c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>ac5f5c4c-c506-4524-b654-e5eac58b3ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/main[1]/main[1]/section[@class=&quot;similiar&quot;]/div[@class=&quot;bg-grey&quot;]/div[@class=&quot;container-lg&quot;]/div[@class=&quot;row d-none d-sm-none d-md-flex&quot;]/div[@class=&quot;col-3&quot;]/p[@class=&quot;title-header&quot;]</value>
      <webElementGuid>3aabb2f5-34f2-409d-9a85-1ac31d5554de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/main/main/section[3]/div[2]/div/div/div/p</value>
      <webElementGuid>48742b15-79ed-435f-9e0b-0776e4339cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similar Jobs (2)'])[1]/following::p[1]</value>
      <webElementGuid>71e22da6-0024-4d60-b8b5-955a95fdd34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share this job'])[1]/following::p[1]</value>
      <webElementGuid>46691ac8-45a0-40a9-8bfe-36c601e1083a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Marketing Executive'])[1]/preceding::p[4]</value>
      <webElementGuid>f643d68b-c0de-4886-80fe-4612255c3943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design and Multimedia Officer'])[2]/preceding::p[8]</value>
      <webElementGuid>8a0437f0-e1b8-49ac-b935-5189aaac9ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role']/parent::*</value>
      <webElementGuid>130faeee-14d9-43c3-9a74-8559cff18f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/p</value>
      <webElementGuid>ac4e3b6f-a83b-4bff-9a87-f3e0835d43ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Role' or . = 'Role')]</value>
      <webElementGuid>5a36d456-ec0b-4e81-9ca5-c3ae683d5911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
