<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EN</name>
   <tag></tag>
   <elementGuidId>0d757a82-6a4b-49fd-9234-28d5daf21c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='changeLanguage__BV_toggle_']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn-dropdown-language.p-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e307f611-e8d9-434f-815e-e4f48e4cacf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-dropdown-language p-0</value>
      <webElementGuid>aa2fbd17-5966-4d35-b385-e2c6113c3ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EN
              </value>
      <webElementGuid>a7b40c9b-41c1-4631-a632-076c30d6a7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/main[1]/nav[@class=&quot;navbar nav-transparent sticky-top navbar-light navbar-expand-lg&quot;]/div[@class=&quot;container-xl&quot;]/ul[@class=&quot;navbar-nav ml-auto align-items-center d-none d-lg-flex&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link nuxt-link-exact-active nuxt-link-active&quot;]/div[@id=&quot;changeLanguage&quot;]/button[@id=&quot;changeLanguage__BV_toggle_&quot;]/span[@class=&quot;btn-dropdown-language p-0&quot;]</value>
      <webElementGuid>9bf06f8b-f495-4310-b12c-cba877d54e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='changeLanguage__BV_toggle_']/span</value>
      <webElementGuid>a0e0ffc0-d5f3-4eb7-a4dd-f8709d4b8e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us'])[1]/following::span[1]</value>
      <webElementGuid>b57ed2b6-9cd5-47de-b272-8a9b80a69e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Life at Koltiva'])[1]/following::span[1]</value>
      <webElementGuid>73f0ff8f-db5a-43fd-b092-c80a615cfc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Core Values'])[2]/preceding::span[3]</value>
      <webElementGuid>9646013d-70ab-4ce5-971c-81020a0b05f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Life at Koltiva'])[2]/preceding::span[3]</value>
      <webElementGuid>006ee944-b900-4a09-9e15-05cc18209fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EN']/parent::*</value>
      <webElementGuid>0cf35ed3-cef9-462f-a014-2dba59a1469c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>0196d63b-2f4f-40ce-a4bf-59f06d70f46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'EN
              ' or . = 'EN
              ')]</value>
      <webElementGuid>73265f6f-eb97-451b-b447-a7faa1933da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
