<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_F.A.R.M.E.R</name>
   <tag></tag>
   <elementGuidId>620a8eb8-a391-4336-8083-76a72a645293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='values']/div/div/div/h3/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.title-green</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e1142be2-8639-4163-b9f2-7ac0bf1a505a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-green</value>
      <webElementGuid>2d14a468-78dd-4b2e-a0f1-0d6ae8e55bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>F.A.R.M.E.R</value>
      <webElementGuid>23234813-3b51-463c-a97e-e3e3fe9ac639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;values&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-center col-12&quot;]/h3[1]/span[@class=&quot;title-green&quot;]</value>
      <webElementGuid>d41ad12e-5c4d-4ded-9fd1-f0b9be8ab386</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='values']/div/div/div/h3/span</value>
      <webElementGuid>c6400c44-380c-4c8a-a183-a18d53528810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All Positions'])[1]/following::span[1]</value>
      <webElementGuid>97ccae35-a4ff-4b8a-9a57-0398c2d8783c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F - Focus on the Users'])[1]/preceding::span[1]</value>
      <webElementGuid>bc0944d3-6974-48d6-8049-a7841946f75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A - Agility with Growth Mindset'])[1]/preceding::span[1]</value>
      <webElementGuid>40d520ce-98e2-4fc6-9616-3808e2e06fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='F.A.R.M.E.R']/parent::*</value>
      <webElementGuid>812270cf-a82e-464d-8a2f-cc01db4800a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>2533212f-8894-457b-8652-eab113c8c19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'F.A.R.M.E.R' or . = 'F.A.R.M.E.R')]</value>
      <webElementGuid>a5c10175-423e-4f32-b7a9-3771b5f3711f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
