<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Blog</name>
   <tag></tag>
   <elementGuidId>4425d77d-00c1-4cbd-a29b-976932ed9102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='comp-keidh9zf6label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comp-keidh9zf6label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a876123a-3644-48ca-8996-00e6249fc5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>foFAdY</value>
      <webElementGuid>5bf986e4-1000-4a61-9613-cf14dc158db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comp-keidh9zf6label</value>
      <webElementGuid>231d0cf6-c1aa-4b99-a700-206f89108127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>ba08c485-86fd-49f4-844e-d0f1c0d3f443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-keidh9zf6label&quot;)</value>
      <webElementGuid>f220e5fd-dc6a-4214-bd48-5dca601a814f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='comp-keidh9zf6label']</value>
      <webElementGuid>7aaf4b51-46df-44e2-9010-30bcc81684c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='comp-keidh9zf6']/a/div/div/p</value>
      <webElementGuid>318897cf-1502-48be-86d4-8a22f3700a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiPay'])[1]/following::p[4]</value>
      <webElementGuid>3f6e5857-f234-4f6b-8b59-48b141df6e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KoltiTrade'])[1]/following::p[4]</value>
      <webElementGuid>9b86afe6-7d33-4216-90a7-b2018c64cab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Demo'])[1]/preceding::p[3]</value>
      <webElementGuid>d78827db-e80f-417c-9b60-9c037fccc905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>9dab730d-3b0c-4ae9-9e2a-e78de6d4fd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/div/div/p</value>
      <webElementGuid>12eb0b6c-1928-43a5-9f33-24cad1ea874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'comp-keidh9zf6label' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>f0e74f5b-fc1b-40fc-b0f9-cff62e18fc3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
