<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Changes to this Policy</name>
   <tag></tag>
   <elementGuidId>c7895661-fbad-43ae-be6c-960047c7dd0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comp-l1ysg3w61']/p[55]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c93a29c7-fdfe-41fe-876c-a3c8ae57c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wixui-rich-text__text</value>
      <webElementGuid>e955dc2e-3483-4b33-b670-4af168f1dc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Changes to this Policy</value>
      <webElementGuid>cdac699f-da35-4484-93f5-fd8c8cf3dd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comp-l1ysg3w61&quot;)/p[@class=&quot;font_9 wixui-rich-text__text&quot;]/span[@class=&quot;wixui-rich-text__text&quot;]</value>
      <webElementGuid>9ba2c4f3-1e72-4df1-9ea0-eb993e3efc66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comp-l1ysg3w61']/p[55]/span</value>
      <webElementGuid>e53dd3fb-3cc6-4fc6-a72f-5578820205c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[14]/following::span[1]</value>
      <webElementGuid>3acb8cbc-ce87-4e50-b67e-3e5625a677fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Rights'])[1]/following::span[2]</value>
      <webElementGuid>dbb3b4c2-f68e-4435-a836-de0d419092b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[15]/preceding::span[1]</value>
      <webElementGuid>46dbd5d3-2448-4ea0-9a45-d4cf56954108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bottom of page'])[1]/preceding::span[2]</value>
      <webElementGuid>b42b1373-d84d-46a7-b219-a9fe0fa028bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Changes to this Policy']/parent::*</value>
      <webElementGuid>710e5d4c-e392-4418-80ae-b4b5a9f78cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[55]/span</value>
      <webElementGuid>6e6e793c-e8b2-46cd-8e94-f55e93f3b3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Changes to this Policy' or . = 'Changes to this Policy')]</value>
      <webElementGuid>f661d433-0ef1-4e96-b181-3af764e7b4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
